# Generated by Django 2.1.3 on 2018-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Intern', 'Intern')], default='Job', max_length=10)),
                ('slug', models.CharField(default=models.CharField(max_length=50), max_length=50)),
                ('summary', models.TextField()),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Intern', 'Intern')], default='Job', max_length=10)),
                ('slug', models.CharField(default=models.CharField(max_length=50), max_length=50)),
                ('summary', models.TextField()),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
