# Generated by Django 2.1.3 on 2018-12-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstVacancy',
        ),
    ]
